language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t msaifurr/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true msaifurr/docker-react npm run test